name: Release

on:
  release:
    types: [published]

jobs:

  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: check version
        env: 
          GIT_VERSION: ${{ github.ref }}
        run: |
          CARGO_VERSION="v$(egrep '^version\s+=' Cargo.toml | egrep -o '[0-9]+\.[0-9]+\.[0-9]+')"
          echo $CARGO_VERSION $GIT_VERSION
          [ "$GIT_VERSION" = "$CARGO_VERSION" ]
    
  release:
    name: release ${{ matrix.target }}
    needs: check-version
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}

  publish:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
