name: Release Rust Binary

on:
  push:
    tags:
      - 'v*' # Only runs when you push a tag like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build release binary
      run: cargo build --release

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/git-remote-s3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
